### ISSUE TITLE
A few items

### ISSUE THREAD

**Issue by b-t-k** [bobrk/p-g-wodehouse_the-head-of-kays#1]
-run clean again

## se-lint-ignore
- you don’t need the spans in the blockquote. They are there in verse etc to ensure that the indents are respected which is unnecessary in this case. So this exception is also unnecessary.
- not sure why you added an exception for ad infinitum? It is generally italicized as an exception to the rule: [https://standardebooks.org/manual/1.7.3/single-page#8.2.9.9]
(https://standardebooks.org/manual/1.7.3/single-page#8.2.9.9)
## content.opf
- long description: *The Captain* needs italics
## chapter 1
- 'The Coon Band Contest' is a song name and needs song semantics. Are there more that I didn't see? [https://standardebooks.org/vocab/1.0](https://standardebooks.org/vocab/1.0)
- `<em>role</em>` doesn’t need the `<em>`. It was generally italicized in that period as being a “foreign” word, so no semantics needed.

## chapter 11
- ROT… shouldn’t be all caps. [https://standardebooks.org/manual/1.7.3/single-page#8.3.3](https://standardebooks.org/manual/1.7.3/single-page#8.3.3)

## chapter 14
-`<i epub:type="se:name.music.opera">The Outsider</i>` — I think you will find that this is a farce and therefore a play rather than an opera

## chapter 15
- KNOW… shouldn’t be all caps. (See above)

## chapter 16
- you took out too much code in the verse. You need to keep the indents for the second and fourth line.

**Comment by bobrk** [comment]
Ok, all things have been addressed. I changed the list of guests in Chapter 15 to an unsettled unordered list, but I would like to indent the "and" and I'm not sure of the best way to do it.

I also found another song to semanticate and two composer names. 

Thanks for checking this, I learn something every time.
