### ISSUE TITLE
A fix

### ISSUE THREAD

**Issue by b-t-k** [bobrk/p-g-wodehouse_the-head-of-kays#2]
Not sure I agree with a list for chapter 15 but let's leave it for Alex. If you want the indent try adding: 
```
#chapter-15 ul p{
	padding-left: 1em;
	text-indent: -1em;
}
```

**Comment by bobrk** [comment]
Would that code just indent the "and"?

**Comment by b-t-k** [comment]
Yes. It creates a hanging indent for the list items and since you broke the `<p>` with a `<br/>` that line would start indented

**Comment by bobrk** [comment]
Awesome, thanks. I’ll try that.

**Comment by bobrk** [comment]
Looks good, committed and pushed.
